name: release

on:
  push:
    tags:
      - '*.*.*'

permissions:
  contents: write 

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write 
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm ci

      - run: npm run build

      - name: Verify required files
        run: |
          test -f manifest.json
          test -f main.js
          test -f styles.css || true

      - name: Create zip
        run: |
          zip -r python-paste-formatter-$GITHUB_REF_NAME.zip manifest.json main.js styles.css

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          files: |
            manifest.json
            main.js
            python-paste-formatter-${{ github.ref_name }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
